### ISSUE TITLE
macOS Monterey Build Failure

### ISSUE THREAD

**Issue by jmstacey** [Expensify/Bedrock#1142]
Unable to compile on macOS Monterey 12.1 (21C52)

side note: instructions should probably be `brew install gcc@9` instead of gcc@6  ?

Errors on make:
```
bash-3.2$ make

c++ -g -std=c++17 -fpic -DSQLITE_ENABLE_NORMALIZE -O2 -Wall -Werror -Wformat-security -I/Users/jon/Downloads/Bedrock -I/Users/jon/Downloads/Bedrock/mbedtls/include -MMD -MF .build/sqlitecluster/SQLite.d -MT .build/sqlitecluster/SQLite.o -o .build/sqlitecluster/SQLite.o -c sqlitecluster/SQLite.cpp
sqlitecluster/SQLite.cpp:3:10: fatal error: 'linux/limits.h' file not found
#include <linux/limits.h>
         ^~~~~~~~~~~~~~~~
1 error generated.
c++ -g -std=c++17 -fpic -DSQLITE_ENABLE_NORMALIZE -O2 -Wall -Werror -Wformat-security -I/Users/jon/Downloads/Bedrock -I/Users/jon/Downloads/Bedrock/mbedtls/include -MMD -MF .build/main.d -MT .build/main.o -DGIT_REVISION=137b1b2b51 -o .build/main.o -c main.cpp
In file included from main.cpp:12:
In file included from /Users/jon/Downloads/Bedrock/BedrockServer.h:3:
In file included from /Users/jon/Downloads/Bedrock/sqlitecluster/SQLiteNode.h:2:
/Users/jon/Downloads/Bedrock/libstuff/STCPNode.h:137:16: error: class 'STCPNode' was previously declared as a struct; this is valid, but may result in linker errors under the Microsoft C++ ABI [-Werror,-Wmismatched-tags]
        friend class STCPNode;
               ^
/Users/jon/Downloads/Bedrock/libstuff/STCPNode.h:46:8: note: previous use is here
struct STCPNode : public STCPServer {
       ^
In file included from main.cpp:12:
In file included from /Users/jon/Downloads/Bedrock/BedrockServer.h:5:
In file included from /Users/jon/Downloads/Bedrock/BedrockPlugin.h:2:
In file included from /Users/jon/Downloads/Bedrock/BedrockCommand.h:2:
In file included from /Users/jon/Downloads/Bedrock/libstuff/SHTTPSManager.h:3:
/Users/jon/Downloads/Bedrock/libstuff/SData.h:12:1: error: 'SData' defined as a struct here but previously declared as a class; this is valid, but may result in linker errors under the Microsoft C++ ABI [-Werror,-Wmismatched-tags]
struct SData {
^
/Users/jon/Downloads/Bedrock/libstuff/libstuff.h:27:1: note: did you mean struct here?
class SData;
^~~~~
struct
In file included from main.cpp:12:
In file included from /Users/jon/Downloads/Bedrock/BedrockServer.h:5:
In file included from /Users/jon/Downloads/Bedrock/BedrockPlugin.h:2:
In file included from /Users/jon/Downloads/Bedrock/BedrockCommand.h:2:
/Users/jon/Downloads/Bedrock/libstuff/SHTTPSManager.h:83:21: error: 'SHTTPSManager::NotLeading::what' hides overloaded virtual function [-Werror,-Woverloaded-virtual]
        const char* what() {
                    ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/exception:106:25: note: hidden overloaded virtual function 'std::exception::what' declared here: different qualifiers ('const' vs unqualified)
    virtual const char* what() const _NOEXCEPT;
                        ^
In file included from main.cpp:12:
In file included from /Users/jon/Downloads/Bedrock/BedrockServer.h:5:
In file included from /Users/jon/Downloads/Bedrock/BedrockPlugin.h:2:
In file included from /Users/jon/Downloads/Bedrock/BedrockCommand.h:3:
/Users/jon/Downloads/Bedrock/sqlitecluster/SQLiteCommand.h:81:20: error: explicitly defaulted move assignment operator is implicitly deleted [-Werror,-Wdefaulted-function-deleted]
    SQLiteCommand& operator=(SQLiteCommand&& from) = default;
                   ^
/Users/jon/Downloads/Bedrock/sqlitecluster/SQLiteCommand.h:20:18: note: move assignment operator of 'SQLiteCommand' is implicitly deleted because field 'request' is of reference type 'const SData &'
    const SData& request;
                 ^
In file included from main.cpp:12:
/Users/jon/Downloads/Bedrock/BedrockServer.h:173:30: error: private field '_owner' is not used [-Werror,-Wunused-private-field]
        const BedrockServer& _owner;
                             ^
5 errors generated.
make: *** [.build/main.o] Error 1
```

**Comment by senojsitruc** [comment]
There are also a number of other Linux-specific lines of code. I guess they gave up on multi-platform. I gave up when I got to  `sigtimedwait()`.

**Comment by lardinator** [comment]
I used `<limits.h>` on macOS Big Sur and it worked.
There are still errors but I think I solved that one.

**Comment by Zabrane** [comment]
@senojsitruc won't compile on Sequoia `15.6.1`

```bash
$ clang -v
Apple clang version 17.0.0 (clang-1700.0.13.5)
Target: arm64-apple-darwin24.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

$ brew install jinja2-cli

$ git clone https://github.com/Expensify/Bedrock.git
$ cd Bedrock
$ make
[...]
  CC    ssl_tls13_keys.c
  CC    ssl_tls13_client.c
  CC    ssl_tls13_server.c
  CC    ssl_tls13_generic.c
  AR    libmbedtls.a
  RL    libmbedtls.a
  Gen   include/test/test_certs.h
[...]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/deque:265:15: note: in instantiation of template class 'std::__deque_block_size<std::pair<SQLitePeer *, SData>, long>' requested here
  265 |               __deque_block_size<_ValueType, _DiffType>::value
      |               ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/deque:501:20: note: in instantiation of default argument for '__deque_iterator<value_type, pointer, reference, __map_pointer, difference_type>' required here
  501 |   using iterator = __deque_iterator<value_type, pointer, reference, __map_pointer, difference_type>;
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/queue:302:20: note: in instantiation of template class 'std::deque<std::pair<SQLitePeer *, SData>>' requested here
  302 |   typedef typename container_type::value_type value_type;
      |                    ^
/private/tmp/Bedrock/sqlitecluster/SQLiteNode.h:400:37: note: in instantiation of template class 'std::queue<std::pair<SQLitePeer *, SData>>' requested here
  400 |     queue<pair<SQLitePeer*, SData>> _replicateQueue;
      |                                     ^
/private/tmp/Bedrock/libstuff/libstuff.h:27:8: note: forward declaration of 'SData'
   27 | struct SData;
      |        ^
In file included from main.cpp:6:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/iostream:42:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/ios:220:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__locale:15:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__memory/shared_ptr.h:31:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__memory/uninitialized_algorithms.h:13:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__algorithm/copy.h:12:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__algorithm/copy_move_common.h:14:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__algorithm/unwrap_range.h:19:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__utility/pair.h:39:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__type_traits/is_trivially_relocatable.h:29:68: error: incomplete type 'SData' used in type trait expression
   29 | struct __libcpp_is_trivially_relocatable : integral_constant<bool, __is_trivially_relocatable(_Tp)> {};
      |                                                                    ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__utility/pair.h:78:72: note: in instantiation of template class 'std::__libcpp_is_trivially_relocatable<SData>' requested here
   78 |       __conditional_t<__libcpp_is_trivially_relocatable<_T1>::value && __libcpp_is_trivially_relocatable<_T2>::value,
      |                                                                        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/deque:251:34: note: in instantiation of template class 'std::pair<SQLitePeer *, SData>' requested here
  251 |   static const _DiffType value = sizeof(_ValueType) < 256 ? 4096 / sizeof(_ValueType) : 16;
      |                                  ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/deque:265:15: note: in instantiation of template class 'std::__deque_block_size<std::pair<SQLitePeer *, SData>, long>' requested here
  265 |               __deque_block_size<_ValueType, _DiffType>::value
      |               ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/deque:501:20: note: in instantiation of default argument for '__deque_iterator<value_type, pointer, reference, __map_pointer, difference_type>' required here
  501 |   using iterator = __deque_iterator<value_type, pointer, reference, __map_pointer, difference_type>;
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/queue:302:20: note: in instantiation of template class 'std::deque<std::pair<SQLitePeer *, SData>>' requested here
  302 |   typedef typename container_type::value_type value_type;
      |                    ^
/private/tmp/Bedrock/sqlitecluster/SQLiteNode.h:400:37: note: in instantiation of template class 'std::queue<std::pair<SQLitePeer *, SData>>' requested here
  400 |     queue<pair<SQLitePeer*, SData>> _replicateQueue;
      |                                     ^
/private/tmp/Bedrock/libstuff/libstuff.h:27:8: note: forward declaration of 'SData'
   27 | struct SData;
      |        ^
2 errors generated.
c++ -g -std=c++20 -fPIC -DSQLITE_ENABLE_NORMALIZE -O2 -Wall -Werror -Wformat-security -Wno-unqualified-std-cast-call -Wno-error=deprecated-declarations -I/private/tmp/Bedrock -I/private/tmp/Bedrock/mbedtls/include -MMD -MF .build/VMTouch.d -MT .build/VMTouch.o -o .build/VMTouch.o -c VMTouch.cpp
VMTouch.cpp:5:10: fatal error: 'linux/fs.h' file not found
    5 | #include <linux/fs.h>
      |          ^~~~~~~~~~~~
1 error generated.
c++ -g -std=c++20 -fPIC -DSQLITE_ENABLE_NORMALIZE -O2 -Wall -Werror -Wformat-security -Wno-unqualified-std-cast-call -Wno-error=deprecated-declarations -I/private/tmp/Bedrock -I/private/tmp/Bedrock/mbedtls/include -MMD -MF .build/sqlitecluster/SQLite.d -MT .build/sqlitecluster/SQLite.o -o .build/sqlitecluster/SQLite.o -c sqlitecluster/SQLite.cpp
sqlitecluster/SQLite.cpp:3:10: fatal error: 'linux/limits.h' file not found
    3 | #include <linux/limits.h>
      |          ^~~~~~~~~~~~~~~~
1 error generated.
c++ -g -std=c++20 -fPIC -DSQLITE_ENABLE_NORMALIZE -O2 -Wall -Werror -Wformat-security -Wno-unqualified-std-cast-call -Wno-error=deprecated-declarations -I/private/tmp/Bedrock -I/private/tmp/Bedrock/mbedtls/include -MMD -MF .build/main.d -MT .build/main.o -DGIT_REVISION=18d6ab7bc5 -o .build/main.o -c main.cpp
In file included from main.cpp:6:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/iostream:42:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/ios:220:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__locale:15:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__memory/shared_ptr.h:31:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__memory/uninitialized_algorithms.h:13:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__algorithm/copy.h:12:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__algorithm/copy_move_common.h:14:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__algorithm/unwrap_range.h:19:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__utility/pair.h:75:7: error: field has incomplete type 'SData'
   75 |   _T2 second;
      |       ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/deque:251:34: note: in instantiation of template class 'std::pair<SQLitePeer *, SData>' requested here
  251 |   static const _DiffType value = sizeof(_ValueType) < 256 ? 4096 / sizeof(_ValueType) : 16;
      |                                  ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/deque:265:15: note: in instantiation of template class 'std::__deque_block_size<std::pair<SQLitePeer *, SData>, long>' requested here
  265 |               __deque_block_size<_ValueType, _DiffType>::value
      |               ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/deque:501:20: note: in instantiation of default argument for '__deque_iterator<value_type, pointer, reference, __map_pointer, difference_type>' required here
  501 |   using iterator = __deque_iterator<value_type, pointer, reference, __map_pointer, difference_type>;
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/queue:302:20: note: in instantiation of template class 'std::deque<std::pair<SQLitePeer *, SData>>' requested here
  302 |   typedef typename container_type::value_type value_type;
      |                    ^
/private/tmp/Bedrock/sqlitecluster/SQLiteNode.h:400:37: note: in instantiation of template class 'std::queue<std::pair<SQLitePeer *, SData>>' requested here
  400 |     queue<pair<SQLitePeer*, SData>> _replicateQueue;
      |                                     ^
/private/tmp/Bedrock/libstuff/libstuff.h:27:8: note: forward declaration of 'SData'
   27 | struct SData;
      |        ^
In file included from main.cpp:6:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/iostream:42:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/ios:220:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__locale:15:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__memory/shared_ptr.h:31:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__memory/uninitialized_algorithms.h:13:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__algorithm/copy.h:12:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__algorithm/copy_move_common.h:14:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__algorithm/unwrap_range.h:19:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__utility/pair.h:39:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__type_traits/is_trivially_relocatable.h:29:68: error: incomplete type 'SData' used in type trait expression
   29 | struct __libcpp_is_trivially_relocatable : integral_constant<bool, __is_trivially_relocatable(_Tp)> {};
      |                                                                    ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__utility/pair.h:78:72: note: in instantiation of template class 'std::__libcpp_is_trivially_relocatable<SData>' requested here
   78 |       __conditional_t<__libcpp_is_trivially_relocatable<_T1>::value && __libcpp_is_trivially_relocatable<_T2>::value,
      |                                                                        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/deque:251:34: note: in instantiation of template class 'std::pair<SQLitePeer *, SData>' requested here
  251 |   static const _DiffType value = sizeof(_ValueType) < 256 ? 4096 / sizeof(_ValueType) : 16;
      |                                  ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/deque:265:15: note: in instantiation of template class 'std::__deque_block_size<std::pair<SQLitePeer *, SData>, long>' requested here
  265 |               __deque_block_size<_ValueType, _DiffType>::value
      |               ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/deque:501:20: note: in instantiation of default argument for '__deque_iterator<value_type, pointer, reference, __map_pointer, difference_type>' required here
  501 |   using iterator = __deque_iterator<value_type, pointer, reference, __map_pointer, difference_type>;
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/queue:302:20: note: in instantiation of template class 'std::deque<std::pair<SQLitePeer *, SData>>' requested here
  302 |   typedef typename container_type::value_type value_type;
      |                    ^
/private/tmp/Bedrock/sqlitecluster/SQLiteNode.h:400:37: note: in instantiation of template class 'std::queue<std::pair<SQLitePeer *, SData>>' requested here
  400 |     queue<pair<SQLitePeer*, SData>> _replicateQueue;
      |                                     ^
/private/tmp/Bedrock/libstuff/libstuff.h:27:8: note: forward declaration of 'SData'
   27 | struct SData;
      |        ^
2 errors generated.
make: *** [.build/main.o] Error 1
```
